### ISSUE TITLE
Shouldn't be able to import an example Graph that was already loaded

### ISSUE THREAD

**Issue by gkorland** [FalkorDB/falkordb-cloud#59]
![image](https://github.com/FalkorDB/falkordb-cloud/assets/753206/22c26fd4-7467-43dc-89e9-751af941c7da)

**Comment by AviAvni** [comment]
we need a way to delete a graph
(I allwoed to import the same example to just override it and restore it to the original data if the decided to change it)

**Comment by gkorland** [comment]
@AviAvni OK, so please add it explicitly,
